#!/bin/bash

echo "Mount & system info search"
/bin/busybox mount -t ext4 /dev/mmcblk0p$1 /system
[ "`/bin/busybox grep -i ro.build.version.release=4.3 /system/build.prop`" ] && echo "1" > /system/etc/JB43
[ "`/bin/busybox grep -i ro.build.version.release=4.2 /system/build.prop`" ] && echo "1" > /system/etc/JB42
if [ -f /system/etc/JB43 ]; then
	/bin/busybox cp -a /res/misc/jb43/* /
else
	/bin/busybox cp -a /res/misc/jb42/* /
fi
/bin/busybox rm /system/etc/JB43
/bin/busybox rm /system/etc/JB42
umount /system

